ifdef::env-github[]
:warning-caption: :warning:
endif::[]

= `editorconfig-ant-tasks`

https://github.com/ec4j/editorconfig-ant-tasks/blob/master/LICENSE[image:https://img.shields.io/github/license/ec4j/editorconfig-ant-tasks.svg[License]]
http://search.maven.org/#search%7Cga%7C1%7Corg.ec4j.maven[image:https://img.shields.io/maven-central/v/org.ec4j.maven/editorconfig-ant-tasks.svg[Maven
Central]]
http://travis-ci.org/ec4j/editorconfig-ant-tasks[image:https://img.shields.io/travis/ec4j/editorconfig-ant-tasks/master.svg?logo=travis&color=white&label=Travis+CI[Travis CI build status]]
https://ci.appveyor.com/project/ppalaga/editorconfig-ant-tasks[image:https://img.shields.io/appveyor/ci/ppalaga/editorconfig-ant-tasks/master.svg?logo=appveyor&color=white&label=AppVeyor+Windows+CI[AppVeyor Windows CI build status]]

`editorconfig-ant-tasks` is a Maven plugin for checking whether project files comply with format rules
defined in `http://editorconfig.org/[.editorconfig]` files and eventually also for fixing the violations.

WARNING: `editorconfig-ant-tasks` is new. Expect issues of all kinds which is not to say that you should not
https://github.com/ec4j/editorconfig-ant-tasks/issues[report] them :)


== Basic usage

`editorconfig-ant-tasks` requires Java 7+ and Ant 1.8.0+.

To make the build fail if any of your source files does not comply with `.editorconfig` rules, add the following to your project:

[source,xml]
----
  <!-- TODO: Ant example -->
----

In case any violations are detected, you may want to fix them automagically by running

[source,shell]
----
TODO: Ant example
----

== Configuration

TODO

== How it works

See https://github.com/ec4j/editorconfig-maven-plugin#how-it-works

== How to build

Prerequisites:

* Java 7+
* Optionally Maven 3.5.0+, unless you want to use `./mvnw` or `mvnw.bat` delivered by the project

The most common build with unit tests:

[source,shell]
----
./mvnw clean install
----

On Windows:

[source,shell]
----
.\mvnw.cmd clean install
----


== Misc.

* All code and contributions are under link:/LICENSE[Apache License]
* Issues and Discussions: https://github.com/ec4j/editorconfig-ant-tasks/issues
